version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3001:3001"
    networks:
      - default

  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - web
    networks:
      - default
    environment:
      - CYPRESS_baseUrl=http://web:3001   # ←これ！！！超重要！！！！
    entrypoint: ["npx", "cypress", "run", "--config", "baseUrl=http://web:3001"]

networks:
  default:
    driver: bridge
